maph: httplib::detail::case_ignore::hash Struct Reference
httplib::detail::case_ignore::hash Struct Reference
#include <httplib.h>
Public Member Functions
size_t operator() (const std::string &key) const
size_t hash_core (const char *s, size_t l, size_t h) const
Detailed Description
Definition at line 443 of file httplib.h.
Member Function Documentation
hash_core()
size_t httplib::detail::case_ignore::hash::hash_core (const char * s, size_t l, size_t h) const inline
Definition at line 448 of file httplib.h.
References hash_core(), and httplib::detail::case_ignore::to_lower().
Referenced by hash_core(), and operator()().
operator()()
size_t httplib::detail::case_ignore::hash::operator() (const std::string & key) const inline
Definition at line 444 of file httplib.h.
References hash_core().
The documentation for this struct was generated from the following file:
integrations/rest_api/httplib.h