maph: integrations/rest_api/maph_server_simple.cpp File Reference
maph_server_simple.cpp File Reference
Simple REST API server for maph using cpp-httplib.
#include "maph.hpp"
#include "httplib.h"
#include <filesystem>
#include <unordered_map>
#include <shared_mutex>
#include <atomic>
#include <sstream>
#include <fstream>
#include <algorithm>
#include <cctype>
Classes
class SimpleJSON
class StoreRegistry
Functions
std::string normalize_json (const std::string &json)
std::string minimal_normalize_json (const std::string &json)
int main (int argc, char *argv[])
Detailed Description
Simple REST API server for maph using cpp-httplib.
Single-header HTTP library for easier compilation
Definition in file maph_server_simple.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 265 of file maph_server_simple.cpp.
References SimpleJSON::begin_array(), SimpleJSON::begin_object(), httplib::Request::body, StoreRegistry::create(), httplib::Server::Delete(), SimpleJSON::end_array(), SimpleJSON::end_object(), httplib::Server::Get(), maph::Maph::get(), SimpleJSON::key(), StoreRegistry::list_json(), httplib::Server::listen(), httplib::Request::matches, minimal_normalize_json(), httplib::Server::Options(), maph::Maph::parallel_mset(), httplib::Server::Post(), httplib::Server::Put(), StoreRegistry::remove(), maph::Maph::remove(), maph::Maph::scan(), maph::Maph::set(), httplib::Response::set_content(), httplib::Response::set_header(), httplib::Server::set_post_routing_handler(), maph::Maph::stats(), httplib::Response::status, SimpleJSON::str(), SimpleJSON::value(), and StoreRegistry::with_store().
minimal_normalize_json()
std::string minimal_normalize_json (const std::string & json)
Definition at line 81 of file maph_server_simple.cpp.
Referenced by main().
normalize_json()
std::string normalize_json (const std::string & json)
Definition at line 23 of file maph_server_simple.cpp.