maph: integrations/rest_api/_deps/usockets-src/src/bsd.c File Reference
bsd.c File Reference
#include "libusockets.h"
#include "internal/internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <netdb.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/un.h>
#include <sys/stat.h>
#include <stddef.h>
Classes
struct us_internal_udp_packet_buffer
Macros
#define __APPLE_USE_RFC_3542
#define MSG_NOSIGNAL 0
#define IPV6_RECVPKTINFO IPV6_PKTINFO
Functions
int bsd_sendmmsg (int fd, void *msgvec, unsigned int vlen, int flags)
int bsd_recvmmsg (int fd, void *msgvec, unsigned int vlen, int flags, void *timeout)
int bsd_udp_packet_buffer_local_ip (void *msgvec, int index, char *ip)
char * bsd_udp_packet_buffer_peer (void *msgvec, int index)
char * bsd_udp_packet_buffer_payload (void *msgvec, int index)
int bsd_udp_packet_buffer_payload_length (void *msgvec, int index)
void bsd_udp_buffer_set_packet_payload (struct us_udp_packet_buffer_t *send_buf, int index, int offset, void *payload, int length, void *peer_addr)
void * bsd_create_udp_packet_buffer ()
int apple_no_sigpipe (int fd)
int bsd_set_nonblocking (int fd)
void bsd_socket_nodelay (int fd, int enabled)
void bsd_socket_flush (int fd)
int bsd_create_socket (int domain, int type, int protocol)
void bsd_close_socket (int fd)
void bsd_shutdown_socket (int fd)
void bsd_shutdown_socket_read (int fd)
void internal_finalize_bsd_addr (struct bsd_addr_t *addr)
int bsd_local_addr (int fd, struct bsd_addr_t *addr)
int bsd_remote_addr (int fd, struct bsd_addr_t *addr)
char * bsd_addr_get_ip (struct bsd_addr_t *addr)
int bsd_addr_get_ip_length (struct bsd_addr_t *addr)
int bsd_addr_get_port (struct bsd_addr_t *addr)
int bsd_accept_socket (int fd, struct bsd_addr_t *addr)
int bsd_recv (int fd, void *buf, int length, int flags)
int bsd_send (int fd, const char *buf, int length, int msg_more)
int bsd_would_block ()
int bsd_create_listen_socket (const char *host, int port, int options)
int bsd_create_listen_socket_unix (const char *path, int options)
int bsd_create_udp_socket (const char *host, int port)
int bsd_udp_packet_buffer_ecn (void *msgvec, int index)
int bsd_create_connect_socket (const char *host, int port, const char *source_host, int options)
int bsd_create_connect_socket_unix (const char *server_path, int options)
Class Documentation
us_internal_udp_packet_buffer
struct us_internal_udp_packet_buffer
Definition at line 42 of file bsd.c.
Class Members
struct sockaddr_storage addr[LIBUS_UDP_MAX_NUM]
char control[LIBUS_UDP_MAX_NUM][256]
struct iovec iov[LIBUS_UDP_MAX_NUM]
struct mmsghdr msgvec[LIBUS_UDP_MAX_NUM]
Macro Definition Documentation
__APPLE_USE_RFC_3542
#define __APPLE_USE_RFC_3542
Definition at line 20 of file bsd.c.
IPV6_RECVPKTINFO
#define IPV6_RECVPKTINFO IPV6_PKTINFO
MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
Function Documentation
apple_no_sigpipe()
int apple_no_sigpipe (int fd)
Definition at line 259 of file bsd.c.
References LIBUS_SOCKET_ERROR.
Referenced by bsd_accept_socket(), and bsd_create_socket().
bsd_accept_socket()
int bsd_accept_socket (int fd, struct bsd_addr_t * addr)
Definition at line 373 of file bsd.c.
References apple_no_sigpipe(), bsd_set_nonblocking(), internal_finalize_bsd_addr(), bsd_addr_t::len, LIBUS_SOCKET_DESCRIPTOR, LIBUS_SOCKET_ERROR, and bsd_addr_t::mem.
Referenced by us_internal_dispatch_ready_poll().
bsd_addr_get_ip()
char * bsd_addr_get_ip (struct bsd_addr_t * addr)
Definition at line 360 of file bsd.c.
References bsd_addr_t::ip.
Referenced by us_internal_dispatch_ready_poll(), and us_socket_remote_address().
bsd_addr_get_ip_length()
int bsd_addr_get_ip_length (struct bsd_addr_t * addr)
Definition at line 364 of file bsd.c.
References bsd_addr_t::ip_length.
Referenced by us_internal_dispatch_ready_poll(), and us_socket_remote_address().
bsd_addr_get_port()
int bsd_addr_get_port (struct bsd_addr_t * addr)
Definition at line 368 of file bsd.c.
References bsd_addr_t::port.
Referenced by us_create_udp_socket(), and us_socket_local_port().
bsd_close_socket()
void bsd_close_socket (int fd)
Definition at line 302 of file bsd.c.
Referenced by bsd_create_connect_socket(), bsd_create_listen_socket(), bsd_create_listen_socket_unix(), bsd_create_udp_socket(), us_listen_socket_close(), us_socket_close(), and us_socket_close_connecting().
bsd_create_connect_socket()
int bsd_create_connect_socket (const char * host, int port, const char * source_host, int options)
Definition at line 668 of file bsd.c.
References bsd_close_socket(), bsd_create_socket(), LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_socket_context_connect().
bsd_create_connect_socket_unix()
int bsd_create_connect_socket_unix (const char * server_path, int options)
Definition at line 706 of file bsd.c.
References bsd_create_socket(), LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_socket_context_connect_unix().
bsd_create_listen_socket()
int bsd_create_listen_socket (const char * host, int port, int options)
Definition at line 432 of file bsd.c.
References bsd_close_socket(), bsd_create_socket(), LIBUS_LISTEN_EXCLUSIVE_PORT, LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_socket_context_listen().
bsd_create_listen_socket_unix()
int bsd_create_listen_socket_unix (const char * path, int options)
Definition at line 514 of file bsd.c.
References bsd_close_socket(), bsd_create_socket(), LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_socket_context_listen_unix().
bsd_create_socket()
int bsd_create_socket (int domain, int type, int protocol)
Definition at line 290 of file bsd.c.
References apple_no_sigpipe(), bsd_set_nonblocking(), and LIBUS_SOCKET_DESCRIPTOR.
Referenced by bsd_create_connect_socket(), bsd_create_connect_socket_unix(), bsd_create_listen_socket(), bsd_create_listen_socket_unix(), and bsd_create_udp_socket().
bsd_create_udp_packet_buffer()
void * bsd_create_udp_packet_buffer ()
Definition at line 225 of file bsd.c.
References us_internal_udp_packet_buffer::addr, us_internal_udp_packet_buffer::control, us_internal_udp_packet_buffer::iov, LIBUS_UDP_MAX_NUM, LIBUS_UDP_MAX_SIZE, and us_internal_udp_packet_buffer::msgvec.
Referenced by us_create_udp_packet_buffer().
bsd_create_udp_socket()
int bsd_create_udp_socket (const char * host, int port)
Definition at line 550 of file bsd.c.
References bsd_close_socket(), bsd_create_socket(), IPV6_RECVPKTINFO, LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_create_udp_socket().
bsd_local_addr()
int bsd_local_addr (int fd, struct bsd_addr_t * addr)
Definition at line 342 of file bsd.c.
References internal_finalize_bsd_addr(), bsd_addr_t::len, and bsd_addr_t::mem.
Referenced by us_create_udp_socket(), and us_socket_local_port().
bsd_recv()
int bsd_recv (int fd, void * buf, int length, int flags)
Definition at line 396 of file bsd.c.
Referenced by us_internal_dispatch_ready_poll().
bsd_recvmmsg()
int bsd_recvmmsg (int fd, void * msgvec, unsigned int vlen, int flags, void * timeout)
Definition at line 111 of file bsd.c.
References us_internal_udp_packet_buffer::addr, LIBUS_UDP_MAX_NUM, LIBUS_UDP_MAX_SIZE, and us_internal_udp_packet_buffer::msgvec.
Referenced by us_udp_socket_receive().
bsd_remote_addr()
int bsd_remote_addr (int fd, struct bsd_addr_t * addr)
Definition at line 351 of file bsd.c.
References internal_finalize_bsd_addr(), bsd_addr_t::len, and bsd_addr_t::mem.
Referenced by us_socket_remote_address().
bsd_send()
int bsd_send (int fd, const char * buf, int length, int msg_more)
Definition at line 400 of file bsd.c.
References MSG_NOSIGNAL.
Referenced by us_socket_write().
bsd_sendmmsg()
int bsd_sendmmsg (int fd, void * msgvec, unsigned int vlen, int flags)
Definition at line 56 of file bsd.c.
References us_internal_udp_packet_buffer::addr, LIBUS_UDP_MAX_NUM, MSG_NOSIGNAL, and us_internal_udp_packet_buffer::msgvec.
Referenced by us_udp_socket_send().
bsd_set_nonblocking()
int bsd_set_nonblocking (int fd)
Definition at line 269 of file bsd.c.
Referenced by bsd_accept_socket(), and bsd_create_socket().
bsd_shutdown_socket()
void bsd_shutdown_socket (int fd)
Definition at line 310 of file bsd.c.
Referenced by us_socket_shutdown().
bsd_shutdown_socket_read()
void bsd_shutdown_socket_read (int fd)
Definition at line 318 of file bsd.c.
Referenced by us_socket_shutdown_read().
bsd_socket_flush()
void bsd_socket_flush (int fd)
Definition at line 282 of file bsd.c.
Referenced by us_socket_flush().
bsd_socket_nodelay()
void bsd_socket_nodelay (int fd, int enabled)
Definition at line 278 of file bsd.c.
Referenced by us_internal_dispatch_ready_poll().
bsd_udp_buffer_set_packet_payload()
void bsd_udp_buffer_set_packet_payload (struct us_udp_packet_buffer_t * send_buf, int index, int offset, void * payload, int length, void * peer_addr)
Definition at line 193 of file bsd.c.
References us_internal_udp_packet_buffer::addr.
Referenced by us_udp_buffer_set_packet_payload().
bsd_udp_packet_buffer_ecn()
int bsd_udp_packet_buffer_ecn (void * msgvec, int index)
Definition at line 637 of file bsd.c.
Referenced by us_udp_packet_buffer_ecn().
bsd_udp_packet_buffer_local_ip()
int bsd_udp_packet_buffer_local_ip (void * msgvec, int index, char * ip)
Definition at line 141 of file bsd.c.
Referenced by us_udp_packet_buffer_local_ip().
bsd_udp_packet_buffer_payload()
char * bsd_udp_packet_buffer_payload (void * msgvec, int index)
Definition at line 175 of file bsd.c.
References us_internal_udp_packet_buffer::msgvec.
Referenced by us_udp_packet_buffer_payload().
bsd_udp_packet_buffer_payload_length()
int bsd_udp_packet_buffer_payload_length (void * msgvec, int index)
Definition at line 184 of file bsd.c.
References us_internal_udp_packet_buffer::msgvec.
Referenced by us_udp_packet_buffer_payload_length().
bsd_udp_packet_buffer_peer()
char * bsd_udp_packet_buffer_peer (void * msgvec, int index)
Definition at line 166 of file bsd.c.
References us_internal_udp_packet_buffer::addr, and us_internal_udp_packet_buffer::msgvec.
Referenced by us_udp_packet_buffer_peer().
bsd_would_block()
int bsd_would_block ()
Definition at line 422 of file bsd.c.
Referenced by us_internal_dispatch_ready_poll().
internal_finalize_bsd_addr()
void internal_finalize_bsd_addr (struct bsd_addr_t * addr)
Definition at line 326 of file bsd.c.
References bsd_addr_t::ip, bsd_addr_t::ip_length, bsd_addr_t::mem, and bsd_addr_t::port.
Referenced by bsd_accept_socket(), bsd_local_addr(), and bsd_remote_addr().