maph: integrations/rest_api/_deps/usockets-src/src/internal/networking/bsd.h File Reference
bsd.h File Reference
#include "libusockets.h"
#include <sys/socket.h>
Classes
struct bsd_addr_t
Macros
#define _GNU_SOURCE
#define SETSOCKOPT_PTR_TYPE int *
#define LIBUS_SOCKET_ERROR -1
#define LIBUS_UDP_MAX_SIZE (64 * 1024)
#define LIBUS_UDP_MAX_NUM 1024
Functions
int bsd_sendmmsg (LIBUS_SOCKET_DESCRIPTOR fd, void *msgvec, unsigned int vlen, int flags)
int bsd_recvmmsg (LIBUS_SOCKET_DESCRIPTOR fd, void *msgvec, unsigned int vlen, int flags, void *timeout)
int bsd_udp_packet_buffer_payload_length (void *msgvec, int index)
char * bsd_udp_packet_buffer_payload (void *msgvec, int index)
char * bsd_udp_packet_buffer_peer (void *msgvec, int index)
int bsd_udp_packet_buffer_local_ip (void *msgvec, int index, char *ip)
int bsd_udp_packet_buffer_ecn (void *msgvec, int index)
void * bsd_create_udp_packet_buffer ()
void bsd_udp_buffer_set_packet_payload (struct us_udp_packet_buffer_t *send_buf, int index, int offset, void *payload, int length, void *peer_addr)
LIBUS_SOCKET_DESCRIPTOR apple_no_sigpipe (LIBUS_SOCKET_DESCRIPTOR fd)
LIBUS_SOCKET_DESCRIPTOR bsd_set_nonblocking (LIBUS_SOCKET_DESCRIPTOR fd)
void bsd_socket_nodelay (LIBUS_SOCKET_DESCRIPTOR fd, int enabled)
void bsd_socket_flush (LIBUS_SOCKET_DESCRIPTOR fd)
LIBUS_SOCKET_DESCRIPTOR bsd_create_socket (int domain, int type, int protocol)
void bsd_close_socket (LIBUS_SOCKET_DESCRIPTOR fd)
void bsd_shutdown_socket (LIBUS_SOCKET_DESCRIPTOR fd)
void bsd_shutdown_socket_read (LIBUS_SOCKET_DESCRIPTOR fd)
void internal_finalize_bsd_addr (struct bsd_addr_t *addr)
int bsd_local_addr (LIBUS_SOCKET_DESCRIPTOR fd, struct bsd_addr_t *addr)
int bsd_remote_addr (LIBUS_SOCKET_DESCRIPTOR fd, struct bsd_addr_t *addr)
char * bsd_addr_get_ip (struct bsd_addr_t *addr)
int bsd_addr_get_ip_length (struct bsd_addr_t *addr)
int bsd_addr_get_port (struct bsd_addr_t *addr)
LIBUS_SOCKET_DESCRIPTOR bsd_accept_socket (LIBUS_SOCKET_DESCRIPTOR fd, struct bsd_addr_t *addr)
int bsd_recv (LIBUS_SOCKET_DESCRIPTOR fd, void *buf, int length, int flags)
int bsd_send (LIBUS_SOCKET_DESCRIPTOR fd, const char *buf, int length, int msg_more)
int bsd_would_block ()
LIBUS_SOCKET_DESCRIPTOR bsd_create_listen_socket (const char *host, int port, int options)
LIBUS_SOCKET_DESCRIPTOR bsd_create_listen_socket_unix (const char *path, int options)
LIBUS_SOCKET_DESCRIPTOR bsd_create_udp_socket (const char *host, int port)
LIBUS_SOCKET_DESCRIPTOR bsd_create_connect_socket (const char *host, int port, const char *source_host, int options)
LIBUS_SOCKET_DESCRIPTOR bsd_create_connect_socket_unix (const char *server_path, int options)
Class Documentation
bsd_addr_t
struct bsd_addr_t
Definition at line 50 of file bsd.h.
Class Members
char * ip
int ip_length
socklen_t len
struct sockaddr_storage mem
int port
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 39 of file bsd.h.
LIBUS_SOCKET_ERROR
#define LIBUS_SOCKET_ERROR -1
Definition at line 44 of file bsd.h.
LIBUS_UDP_MAX_NUM
#define LIBUS_UDP_MAX_NUM 1024
Definition at line 48 of file bsd.h.
LIBUS_UDP_MAX_SIZE
#define LIBUS_UDP_MAX_SIZE (64 * 1024)
Definition at line 47 of file bsd.h.
SETSOCKOPT_PTR_TYPE
#define SETSOCKOPT_PTR_TYPE int *
Definition at line 43 of file bsd.h.
Function Documentation
apple_no_sigpipe()
LIBUS_SOCKET_DESCRIPTOR apple_no_sigpipe (LIBUS_SOCKET_DESCRIPTOR fd)
bsd_accept_socket()
LIBUS_SOCKET_DESCRIPTOR bsd_accept_socket (LIBUS_SOCKET_DESCRIPTOR fd, struct bsd_addr_t * addr)
bsd_addr_get_ip()
char * bsd_addr_get_ip (struct bsd_addr_t * addr)
Definition at line 360 of file bsd.c.
References bsd_addr_t::ip.
Referenced by us_internal_dispatch_ready_poll(), and us_socket_remote_address().
bsd_addr_get_ip_length()
int bsd_addr_get_ip_length (struct bsd_addr_t * addr)
Definition at line 364 of file bsd.c.
References bsd_addr_t::ip_length.
Referenced by us_internal_dispatch_ready_poll(), and us_socket_remote_address().
bsd_addr_get_port()
int bsd_addr_get_port (struct bsd_addr_t * addr)
Definition at line 368 of file bsd.c.
References bsd_addr_t::port.
Referenced by us_create_udp_socket(), and us_socket_local_port().
bsd_close_socket()
void bsd_close_socket (LIBUS_SOCKET_DESCRIPTOR fd)
bsd_create_connect_socket()
LIBUS_SOCKET_DESCRIPTOR bsd_create_connect_socket (const char * host, int port, const char * source_host, int options)
Definition at line 668 of file bsd.c.
References bsd_close_socket(), bsd_create_socket(), LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_socket_context_connect().
bsd_create_connect_socket_unix()
LIBUS_SOCKET_DESCRIPTOR bsd_create_connect_socket_unix (const char * server_path, int options)
Definition at line 706 of file bsd.c.
References bsd_create_socket(), LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_socket_context_connect_unix().
bsd_create_listen_socket()
LIBUS_SOCKET_DESCRIPTOR bsd_create_listen_socket (const char * host, int port, int options)
Definition at line 432 of file bsd.c.
References bsd_close_socket(), bsd_create_socket(), LIBUS_LISTEN_EXCLUSIVE_PORT, LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_socket_context_listen().
bsd_create_listen_socket_unix()
LIBUS_SOCKET_DESCRIPTOR bsd_create_listen_socket_unix (const char * path, int options)
Definition at line 514 of file bsd.c.
References bsd_close_socket(), bsd_create_socket(), LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_socket_context_listen_unix().
bsd_create_socket()
LIBUS_SOCKET_DESCRIPTOR bsd_create_socket (int domain, int type, int protocol)
Definition at line 290 of file bsd.c.
References apple_no_sigpipe(), bsd_set_nonblocking(), and LIBUS_SOCKET_DESCRIPTOR.
Referenced by bsd_create_connect_socket(), bsd_create_connect_socket_unix(), bsd_create_listen_socket(), bsd_create_listen_socket_unix(), and bsd_create_udp_socket().
bsd_create_udp_packet_buffer()
void * bsd_create_udp_packet_buffer ()
Definition at line 225 of file bsd.c.
References us_internal_udp_packet_buffer::addr, us_internal_udp_packet_buffer::control, us_internal_udp_packet_buffer::iov, LIBUS_UDP_MAX_NUM, LIBUS_UDP_MAX_SIZE, and us_internal_udp_packet_buffer::msgvec.
Referenced by us_create_udp_packet_buffer().
bsd_create_udp_socket()
LIBUS_SOCKET_DESCRIPTOR bsd_create_udp_socket (const char * host, int port)
Definition at line 550 of file bsd.c.
References bsd_close_socket(), bsd_create_socket(), IPV6_RECVPKTINFO, LIBUS_SOCKET_DESCRIPTOR, and LIBUS_SOCKET_ERROR.
Referenced by us_create_udp_socket().
bsd_local_addr()
int bsd_local_addr (LIBUS_SOCKET_DESCRIPTOR fd, struct bsd_addr_t * addr)
bsd_recv()
int bsd_recv (LIBUS_SOCKET_DESCRIPTOR fd, void * buf, int length, int flags)
bsd_recvmmsg()
int bsd_recvmmsg (LIBUS_SOCKET_DESCRIPTOR fd, void * msgvec, unsigned int vlen, int flags, void * timeout)
bsd_remote_addr()
int bsd_remote_addr (LIBUS_SOCKET_DESCRIPTOR fd, struct bsd_addr_t * addr)
bsd_send()
int bsd_send (LIBUS_SOCKET_DESCRIPTOR fd, const char * buf, int length, int msg_more)
bsd_sendmmsg()
int bsd_sendmmsg (LIBUS_SOCKET_DESCRIPTOR fd, void * msgvec, unsigned int vlen, int flags)
bsd_set_nonblocking()
LIBUS_SOCKET_DESCRIPTOR bsd_set_nonblocking (LIBUS_SOCKET_DESCRIPTOR fd)
bsd_shutdown_socket()
void bsd_shutdown_socket (LIBUS_SOCKET_DESCRIPTOR fd)
bsd_shutdown_socket_read()
void bsd_shutdown_socket_read (LIBUS_SOCKET_DESCRIPTOR fd)
bsd_socket_flush()
void bsd_socket_flush (LIBUS_SOCKET_DESCRIPTOR fd)
bsd_socket_nodelay()
void bsd_socket_nodelay (LIBUS_SOCKET_DESCRIPTOR fd, int enabled)
bsd_udp_buffer_set_packet_payload()
void bsd_udp_buffer_set_packet_payload (struct us_udp_packet_buffer_t * send_buf, int index, int offset, void * payload, int length, void * peer_addr)
Definition at line 193 of file bsd.c.
References us_internal_udp_packet_buffer::addr.
Referenced by us_udp_buffer_set_packet_payload().
bsd_udp_packet_buffer_ecn()
int bsd_udp_packet_buffer_ecn (void * msgvec, int index)
Definition at line 637 of file bsd.c.
Referenced by us_udp_packet_buffer_ecn().
bsd_udp_packet_buffer_local_ip()
int bsd_udp_packet_buffer_local_ip (void * msgvec, int index, char * ip)
Definition at line 141 of file bsd.c.
Referenced by us_udp_packet_buffer_local_ip().
bsd_udp_packet_buffer_payload()
char * bsd_udp_packet_buffer_payload (void * msgvec, int index)
Definition at line 175 of file bsd.c.
References us_internal_udp_packet_buffer::msgvec.
Referenced by us_udp_packet_buffer_payload().
bsd_udp_packet_buffer_payload_length()
int bsd_udp_packet_buffer_payload_length (void * msgvec, int index)
Definition at line 184 of file bsd.c.
References us_internal_udp_packet_buffer::msgvec.
Referenced by us_udp_packet_buffer_payload_length().
bsd_udp_packet_buffer_peer()
char * bsd_udp_packet_buffer_peer (void * msgvec, int index)
Definition at line 166 of file bsd.c.
References us_internal_udp_packet_buffer::addr, and us_internal_udp_packet_buffer::msgvec.
Referenced by us_udp_packet_buffer_peer().
bsd_would_block()
int bsd_would_block ()
Definition at line 422 of file bsd.c.
Referenced by us_internal_dispatch_ready_poll().
internal_finalize_bsd_addr()
void internal_finalize_bsd_addr (struct bsd_addr_t * addr)
Definition at line 326 of file bsd.c.
References bsd_addr_t::ip, bsd_addr_t::ip_length, bsd_addr_t::mem, and bsd_addr_t::port.
Referenced by bsd_accept_socket(), bsd_local_addr(), and bsd_remote_addr().