maph: us_internal_udp_t Struct Reference
us_internal_udp_t Struct Reference
Public Attributes
struct us_internal_callback_t cb
struct us_udp_packet_buffer_t * receive_buf
void(* data_cb)(struct us_udp_socket_t *, struct us_udp_packet_buffer_t *, int)
void(* drain_cb)(struct us_udp_socket_t *)
void * user
int port
Detailed Description
Definition at line 67 of file udp.c.
Member Data Documentation
cb
struct us_internal_callback_t us_internal_udp_t::cb
Definition at line 68 of file udp.c.
Referenced by us_create_udp_socket().
data_cb
void(* us_internal_udp_t::data_cb) (struct us_udp_socket_t *, struct us_udp_packet_buffer_t *, int)
Definition at line 70 of file udp.c.
Referenced by internal_on_udp_read(), and us_create_udp_socket().
drain_cb
void(* us_internal_udp_t::drain_cb) (struct us_udp_socket_t *)
Definition at line 71 of file udp.c.
Referenced by us_create_udp_socket().
port
int us_internal_udp_t::port
Definition at line 76 of file udp.c.
Referenced by us_create_udp_socket().
receive_buf
struct us_udp_packet_buffer_t* us_internal_udp_t::receive_buf
Definition at line 69 of file udp.c.
Referenced by internal_on_udp_read(), and us_create_udp_socket().
user
void* us_internal_udp_t::user
Definition at line 72 of file udp.c.
Referenced by us_create_udp_socket(), and us_udp_socket_user().
The documentation for this struct was generated from the following file:
integrations/rest_api/_deps/usockets-src/src/udp.c